---
deployment_env: dev

# Copy backend files from Anisble to the server
backend_copy_build: false

# Copy angular-ssr files from Anisble to the server
angular_ssr_copy_build: false

# Expose backend port at host
expose_backend_port: false

# Expose backend to the SWAG-internal proxy
deploy_backend: true
deploy_angular_ssr: true
deploy_landpage: true

# Base domain URLs
swag_external_url: "dev.airconcheck.com"
swag_internal_url: "dev.airconcheck.com"

# Backend (external API)
backend_api_host: "https://api.dev.airconcheck.com"

# Homepage
homepage_allowed_hosts: "homepage.dev.airconcheck.com"

# Internal SWAG exposed services
swag_internal_services:
  - name: portainer
    port: 9000
  - name: netdata
    port: 19999

# CoreDNS enabled by default in dev
coredns_enabled: true
coredns_passthrough_domains:
  - mail.airconcheck.com
coredns_zones:
  - zone: dev.airconcheck.com
    records:
      - type: A
        name: '@'
        value: TAILSCALE_SELF
      - type: A
        name: '*'
        value: TAILSCALE_SELF

# Reconfigurar RS a DNS p√∫blicos (dev) en dos fases
mongodb_public_member_dns: true

# Mongo PBM backup defaults (dev)
mongo_pbm_s3_prefix: "dev/"
