---
# Restart SWAG containers when config changes

- name: restart swag-external
  community.docker.docker_container:
    name: swag-external
    state: started
    restart: true

- name: restart swag-internal
  community.docker.docker_container:
    name: swag-internal
    state: started
    restart: true

- name: restart zabbix-agent2
  systemd:
    name: zabbix-agent2
    state: restarted

- name: restart docker-proxy-socat
  systemd:
    name: docker-proxy-socat
    state: restarted
